"""
Service Bus Package

Azure Service Bus emulator components.

Author: Ayodele Oladeji
Date: 2025-12-05
"""

from .logging_utils import (
    StructuredLogger,
    CorrelationContext,
    configure_logging,
    track_operation_time,
)
from .middleware import CorrelationMiddleware
from .exceptions import (
    ServiceBusError,
    EntityError,
    EntityNotFoundError,
    EntityAlreadyExistsError,
    InvalidEntityNameError,
    QueueNotFoundError,
    QueueAlreadyExistsError,
    InvalidQueueNameError,
    TopicNotFoundError,
    TopicAlreadyExistsError,
    SubscriptionNotFoundError,
    SubscriptionAlreadyExistsError,
    RuleNotFoundError,
    RuleAlreadyExistsError,
    MessageError,
    MessageNotFoundError,
    MessageSizeExceededError,
    MessageLockLostError,
    SessionError,
    SessionNotFoundError,
    SessionLockLostError,
    SessionAlreadyLockedError,
    QuotaExceededError,
    InvalidOperationError,
    TimeoutError,
    ServiceBusConnectionError,
    DeadLetterReason,
    is_transient_error,
)
from .resilience import (
    OperationType,
    TimeoutConfig,
    RetryConfig,
    with_timeout,
    with_retry,
    CircuitBreaker,
    CircuitState,
    CircuitBreakerError,
    get_circuit_breaker,
    with_circuit_breaker,
)
from .error_models import (
    ErrorDetails,
    ErrorInfo,
    ErrorResponse,
)
from .models import (
    QueueDescription,
    QueueProperties,
    QueueRuntimeInfo,
    QueueNameValidator,
    CreateQueueRequest,
    UpdateQueueRequest,
    ServiceBusMessage,
    SendMessageRequest,
    ReceiveMode,
    TopicDescription,
    TopicProperties,
    TopicRuntimeInfo,
    SubscriptionDescription,
    SubscriptionProperties,
    SubscriptionRuntimeInfo,
    SubscriptionFilter,
    FilterType,
    RuleDescription,
    CreateTopicRequest,
    UpdateTopicRequest,
    CreateSubscriptionRequest,
    UpdateSubscriptionRequest,
)

__all__ = [
    # Logging
    "StructuredLogger",
    "CorrelationContext",
    "configure_logging",
    "track_operation_time",
    "CorrelationMiddleware",
    # Exceptions
    "ServiceBusError",
    "EntityError",
    "EntityNotFoundError",
    "EntityAlreadyExistsError",
    "InvalidEntityNameError",
    "QueueNotFoundError",
    "QueueAlreadyExistsError",
    "InvalidQueueNameError",
    "TopicNotFoundError",
    "TopicAlreadyExistsError",
    "SubscriptionNotFoundError",
    "SubscriptionAlreadyExistsError",
    "RuleNotFoundError",
    "RuleAlreadyExistsError",
    "MessageError",
    "MessageNotFoundError",
    "MessageSizeExceededError",
    "MessageLockLostError",
    "SessionError",
    "SessionNotFoundError",
    "SessionLockLostError",
    "SessionAlreadyLockedError",
    "QuotaExceededError",
    "InvalidOperationError",
    "TimeoutError",
    "ServiceBusConnectionError",
    "DeadLetterReason",
    "is_transient_error",
    # Resilience
    "OperationType",
    "TimeoutConfig",
    "RetryConfig",
    "with_timeout",
    "with_retry",
    "CircuitBreaker",
    "CircuitState",
    "CircuitBreakerError",
    "get_circuit_breaker",
    "with_circuit_breaker",
    # Error Models
    "ErrorDetails",
    "ErrorInfo",
    "ErrorResponse",
    # Models
    "QueueDescription",
    "QueueProperties",
    "QueueRuntimeInfo",
    "QueueNameValidator",
    "CreateQueueRequest",
    "UpdateQueueRequest",
    "ServiceBusMessage",
    "SendMessageRequest",
    "ReceiveMode",
    "TopicDescription",
    "TopicProperties",
    "TopicRuntimeInfo",
    "SubscriptionDescription",
    "SubscriptionProperties",
    "SubscriptionRuntimeInfo",
    "SubscriptionFilter",
    "FilterType",
    "RuleDescription",
    "CreateTopicRequest",
    "UpdateTopicRequest",
    "CreateSubscriptionRequest",
    "UpdateSubscriptionRequest",
]
