"""Gateway module for LocalZure.

This module provides URL rewriting, hostname mapping, request routing,
authentication validation, and protocol routing for Azure SDK traffic
to local service endpoints.
"""

from localzure.gateway.hostname_mapper import (
    HostnameMapper,
    MappingResult,
    HostnamePattern,
)
from localzure.gateway.canonicalizer import (
    RequestCanonicalizer,
    CanonicalizedRequest,
    CanonicalVersion,
    ServiceType,
    parse_authorization_header,
)
from localzure.gateway.sas_validator import (
    SASValidator,
    SASToken,
    SASPermission,
    SASResourceType,
    SASService,
    SASValidationError,
    get_permission_for_method,
)
from localzure.gateway.protocol_router import (
    ProtocolRouter,
    ProtocolType,
    ProtocolError,
    ProtocolDetector,
    ProtocolContext,
    ConnectionState,
    format_protocol_error,
)
from localzure.gateway.retry_simulator import (
    RetrySimulator,
    TestModeConfig,
    FailurePattern,
    RetryAfterFormat,
    FailureInjectionResult,
    create_error_response,
    parse_test_mode_config,
)
from localzure.gateway.error_formatter import (
    ErrorFormat,
    ServiceType as ErrorServiceType,
    ErrorContext,
    AzureError,
    generate_request_id,
    generate_timestamp_request_id,
    determine_error_format,
    format_error_xml,
    format_error_json,
    create_error_headers,
    create_error_response as create_azure_error_response,
    map_error_code_to_status,
    create_storage_error,
    create_service_bus_error,
    create_key_vault_error,
    create_cosmos_db_error,
    create_generic_error,
    ERROR_CODE_MAPPINGS,
)

__all__ = [
    "HostnameMapper",
    "MappingResult",
    "HostnamePattern",
    "RequestCanonicalizer",
    "CanonicalizedRequest",
    "CanonicalVersion",
    "ServiceType",
    "parse_authorization_header",
    "SASValidator",
    "SASToken",
    "SASPermission",
    "SASResourceType",
    "SASService",
    "SASValidationError",
    "get_permission_for_method",
    "ProtocolRouter",
    "ProtocolType",
    "ProtocolError",
    "ProtocolDetector",
    "ProtocolContext",
    "ConnectionState",
    "format_protocol_error",
    "RetrySimulator",
    "TestModeConfig",
    "FailurePattern",
    "RetryAfterFormat",
    "FailureInjectionResult",
    "create_error_response",
    "parse_test_mode_config",
    "ErrorFormat",
    "ErrorServiceType",
    "ErrorContext",
    "AzureError",
    "generate_request_id",
    "generate_timestamp_request_id",
    "determine_error_format",
    "format_error_xml",
    "format_error_json",
    "create_error_headers",
    "create_azure_error_response",
    "map_error_code_to_status",
    "create_storage_error",
    "create_service_bus_error",
    "create_key_vault_error",
    "create_cosmos_db_error",
    "create_generic_error",
    "ERROR_CODE_MAPPINGS",
]
